#development:
  #adapter: postgresql
  #encoding: unicode
  #database: jerry
  #host: localhost
  #pool: 5
  #username: 
  #password: 

#test:
  #adapter: postgresql
  #encoding: unicode
  #database: store_test
  #pool: 5
  #username: 
  #password:

#production:
  #adapter: postgresql
  #encoding: unicode
  #database: jerry
  #host: localhost
  #pool: 25
  #username: 
  #password: 
