#
# Redis connection settings, per environment
#
# Defaults: host: localhost, port: 6379, db: 1
#
# These will be available in RedisConfig
#

development:
  host: localhost
  port: 6379
  

test:
  host: localhost
  port: 6379
  

qa:
  host: 
  port: 
  

staging:
  host: 
  port: 
  

demo:
  host: 
  port: 
  

production:
  host: ec2-50-17-104-118.compute-1.amazonaws.com
  port: 6379
  
